version: '3'
services:
  redis:
    image: "redis:alpine"
    # command: "redis-server"  
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.0"
    ports: 
      - "9202:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.0    
    ports: 
      - "5602:5601"
    links:
      - elasticsearch
  web:
    image: 4d9d326000e0
    # deploy:
    #   replicas: 2
    #   restart_policy:
    #     condition: on-failure
    ports: 
      - "3000:3000"  
    # environment:
    #   NODE_ENV: production
    links:
      - redis  
      - elasticsearch
    # networks: 
    #   - webnet
    command: "npm start"  
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8081:8080"  
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  
    deploy:
      placement:
        constraints: [node.role == manager]
      # networks:
      #   - webnet  
volumes: 
  esdata:
    driver: local        
# networks:
#   webnet: