version: '3'
services:
  redis:
    image: "jrod1032/airbnb-search-service:reddiscache"
    ports:
      - "6379:6379" 
  elasticsearch:
    image: "jrod1032/airbnb-search-service:esdb"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    command: [ elasticsearch, -E, network.host=0.0.0.0, -E, discovery.zen.ping.unicast.hosts=elasticsearch, -E, discovery.zen.minumum_master_nodes=1 ] 
  nginx:
    image: 'nginx:1'
    ports: 
      - 9200:9200
    command: |
      /bin/bash -c "echo '
      server {
        listen 9200;
        add_header X-Frame-Options "SAMEORIGIN";
        location / {
            proxy_pass http://elasticsearch:9200;
            proxy_http_version 1.1;
            proxy_set_header Connection keep-alive;
            proxy_dockerset_header Upgrade $$http_upgrade;
            proxy_set_header Host $$host;
            proxy_set_header X-Real-IP $$remote_addr;
            proxy_cache_bypass $$http_upgrade;
        }
      }' | tee /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"   
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.0    
    ports: 
      - "5602:5601"
  web:
    image: jrod1032/airbnb-search-service:server1
    ports: 
      - "80:3000"  
    command: "npm start"  
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8081:8080"  
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  
    deploy:
      placement:
        constraints: [node.role == manager]
volumes: 
  esdata:
    driver: local        
# networks:
#   webnet: